services:
  server:
    build:
      context: ./web2
      dockerfile: Dockerfile
    container_name: my_html_server
    ports:
      - "8000:8000"
    restart: unless-stopped
  nginx:
    build: web
    ports:
      - "8080:80"